services:

#  production-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: order-api
#    restart: always
#    networks:
#      - production-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
#      - POSTGRES_DB_URL=jdbc:postgresql://localhost:5432/msproduction
#      - POSTGRES_DB_USERNAME=production_user
#      - POSTGRES_DB_PASSWORD=production_password
#      - AWS_REGION=us-east-1
#      - AWS_ACCESS_KEY_ID=test
#      - AWS_SECRET_ACCESS_KEY=test
#      - SQS_PRODUCTION_QUEUE=production-queue
#      - SQS_PRODUCTION_CALLBACK_QUEUE=production-callback-queue
#    ports:
#      - "8090:8090"
#    depends_on:
#      - postgres
#      - localstack

  postgres:
    image: postgres:17
    container_name: production-postgres
    restart: always
    environment:
      POSTGRES_DB: production_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: production_password
    ports:
      - "5432:5432"
    networks:
      - production-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: production-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      DEBUG: "1"
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SESSION_TOKEN: test
    networks:
      - production-network
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./local/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

volumes:
  pgdata:

networks:
  production-network:
    driver: bridge
