spring:
  application:
    name: msproduction

  flyway:
    enabled: false

  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/production_db}
    username: ${POSTGRES_DB:postgres}
    password: ${POSTGRES_DB_PASSWORD:production_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      sqs:
        endpoint: http://localhost:4566

  sqs:
    queues:
      production-queue: ${SQS_PRODUCTION_QUEUE:production-queue}
      production-callback-queue: ${SQS_PRODUCTION_CALLBACK_QUEUE:production-callback-queue}

server:
  port: 8090