spring:
  application:
    name: msproduction

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/msproduction
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  sqs:
    queues:
      production-queue: ${SQS_PRODUCTION_QUEUE}
      production-callback-queue: ${SQS_PRODUCTION_CALLBACK_QUEUE}

server:
  port: 8090