spring:
  application:
    name: msproduction

  flyway:
    enabled: false

  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/production_db}
    username: ${POSTGRES_DB:postgres}
    password: ${POSTGRES_DB_PASSWORD:production_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}

  sqs:
    queues:
      production-queue: ${SQS_PRODUCTION_QUEUE:production-queue}
      production-callback-queue: ${SQS_PRODUCTION_CALLBACK_QUEUE:production-callback-queue}

server:
  port: 8090