apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-production-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: dev
  AWS_REGION: us-east-1
  SPRING_SQS_QUEUES_PRODUCTION_QUEUE: https://sqs.us-east-1.amazonaws.com/500782030170/production-queue
  SPRING_SQS_QUEUES_PRODUCTION_CALLBACK_QUEUE: https://sqs.us-east-1.amazonaws.com/500782030170/production-callback-queue

