# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: postgresdb
#   namespace: default
# spec:
#   serviceName: postgresdb
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgresdb
#   template:
#     metadata:
#       labels:
#         app: postgresdb
#     spec:
#       containers:
#         - name: postgresdb
#           image: postgres:17
#           ports:
#             - containerPort: 5432
#           env:
#             - name: POSTGRES_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: postgres-secret
#                   key: username
#             - name: POSTGRES_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: postgres-secret
#                   key: password
#             - name: POSTGRES_DB
#               value: production_db
#           volumeMounts:
#             - name: postgres-data
#               mountPath: /var/lib/postgresql/data
#           resources:
#             requests:
#               cpu: 300m
#               memory: 1Gi
#             limits:
#               cpu: 1
#               memory: 2Gi
#   volumeClaimTemplates:
#     - metadata:
#         name: postgres-data
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 5Gi
