name: CD - Production

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CLUSTER_NAME: nextime-cluster
  ECR_REPOSITORY: ms-production
  ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/ms-production

jobs:
  deploy-prod:
    name: Build, Terraform & Deploy (Prod)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # --- INÍCIO: BLOCO DE TESTES DE INTEGRAÇÃO ---
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verificar Docker Compose
        run: docker compose version

      - name: Subir LocalStack (Ambiente de Teste)
        run: docker compose up -d production-localstack

      - name: Garantir permissão do init-aws.sh
        run: chmod +x ./local/init-aws.sh || true

      - name: Aguardar LocalStack
        run: |
          echo "Aguardando LocalStack subir..."
          sleep 25

      - name: Rodar testes e Análise Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=Grupo-202-FIAP_ms-production \
          -Dsonar.organization=grupo-202-fiap \
          -Dsonar.host.url=https://sonarcloud.io

      - name: Derrubar containers de teste

        run: docker compose down -v

        # --- FIM: BLOCO DE TESTES DE INTEGRAÇÃO ---

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e Push da imagem
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_URI:$IMAGE_TAG .
          docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.CLUSTER_NAME }}

      - name: Aplicar manifests do Kubernetes
        working-directory: infra/k8s
        run: kubectl apply -R -f .

      - name: Atualizar Deployment com nova imagem (se existir)
        run: |
          if kubectl get deployment ms-production-deployment >/dev/null 2>&1; then
            kubectl set image deployment/ms-production-deployment \
              ms-production=$ECR_URI:${{ github.sha }}

            kubectl rollout status deployment/ms-production-deployment
          else
            echo "Deployment ms-production-deployment ainda não existe (primeiro deploy)."
          fi
